apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service-secrets-external
  namespace: taskmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: notification-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: EMAIL_USER
      remoteRef:
        key: taskmanager/app
        property: email_user
    - secretKey: EMAIL_APP_PASSWORD
      remoteRef:
        key: taskmanager/app
        property: email_app_password
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: taskmanager/app
        property: internal_api_key
