apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-db-secrets
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: notification-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: microservices/notification-db
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: microservices/notification-db
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: microservices/notification-db
        property: name
    - secretKey: DB_USER
      remoteRef:
        key: microservices/notification-db
        property: user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: microservices/notification-db
        property: password
